<?php

namespace Database\Seeders;

use App\Models\MutualFund;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class MutualFundSeeder extends Seeder
{
    public function run()
    {
        $funds = [
            [
                'name' => 'Vanguard 500 Index Fund (VFIAX)',
                'description' => 'Tracks the S&P 500 Index, providing exposure to 500 of the largest U.S. companies.',
                'min_investment' => 15000.00,
                'risk_level' => 'medium',
                'annual_return' => 12.50,
                'total_aum' => 850000000.00,
                'nav_price' => 415.20,
                'inception_date' => '1976-08-31',
            ],
            [
                'name' => 'Fidelity Contrafund (FCNTX)',
                'description' => 'Invests in companies whose value Fidelity Management & Research believes is not fully recognized by the public.',
                'min_investment' => 25000.00,
                'risk_level' => 'high',
                'annual_return' => 15.80,
                'total_aum' => 110000000.00,
                'nav_price' => 18.54,
                'inception_date' => '1967-05-17',
            ],
            [
                'name' => 'T. Rowe Price Blue Chip Growth (TRBCX)',
                'description' => 'Focuses on large-cap companies with the potential for above-average earnings growth.',
                'min_investment' => 15000.00,
                'risk_level' => 'high',
                'annual_return' => 14.20,
                'total_aum' => 95000000.00,
                'nav_price' => 156.30,
                'inception_date' => '1993-06-30',
            ],
            [
                'name' => 'Dodge & Cox Stock Fund (DODGX)',
                'description' => 'A value-oriented fund that invests primarily in medium-to-large-cap U.S. companies.',
                'min_investment' => 20000.00,
                'risk_level' => 'medium',
                'annual_return' => 10.50,
                'total_aum' => 70000000.00,
                'nav_price' => 224.15,
                'inception_date' => '1965-01-04',
            ],
            [
                'name' => 'Vanguard Total Stock Market Index (VTSAX)',
                'description' => 'Provides exposure to the entire U.S. equity market, including small, mid, and large-cap stocks.',
                'min_investment' => 18000.00,
                'risk_level' => 'medium',
                'annual_return' => 11.80,
                'total_aum' => 1300000000.00,
                'nav_price' => 112.45,
                'inception_date' => '1992-04-27',
            ],
            [
                'name' => 'BlackRock Global Allocation (MDLOX)',
                'description' => 'Invests in a diversified portfolio of stocks, bonds, and cash equivalents globally.',
                'min_investment' => 15000.00,
                'risk_level' => 'low',
                'annual_return' => 8.40,
                'total_aum' => 45000000.00,
                'nav_price' => 21.10,
                'inception_date' => '1989-02-03',
            ],
            [
                'name' => 'Fidelity Growth Company (FDGRX)',
                'description' => 'Invests in companies that Fidelity Management & Research believes have above-average growth potential.',
                'min_investment' => 50000.00,
                'risk_level' => 'high',
                'annual_return' => 19.50,
                'total_aum' => 60000000.00,
                'nav_price' => 32.78,
                'inception_date' => '1983-01-17',
            ],
            [
                'name' => 'American Funds Enrollment Fund (ANCFX)',
                'description' => 'A fundamental growth fund looking for long-term capital appreciation.',
                'min_investment' => 15000.00,
                'risk_level' => 'medium',
                'annual_return' => 11.20,
                'total_aum' => 180000000.00,
                'nav_price' => 65.40,
                'inception_date' => '1973-12-01',
            ],
            [
                'name' => 'PIMCO Total Return (PTTRX)',
                'description' => 'One of the world\'s largest active bond funds, aiming for maximum total return.',
                'min_investment' => 100000.00,
                'risk_level' => 'low',
                'annual_return' => 5.20,
                'total_aum' => 55000000.00,
                'nav_price' => 10.05,
                'inception_date' => '1987-05-11',
            ],
            [
                'name' => 'Vanguard Growth Index Fund (VIGAX)',
                'description' => 'Focuses on large-cap U.S. companies in sectors with high growth potential.',
                'min_investment' => 15000.00,
                'risk_level' => 'high',
                'annual_return' => 16.10,
                'total_aum' => 150000000.00,
                'nav_price' => 145.80,
                'inception_date' => '1998-11-13',
            ],
            [
                'name' => 'Schwab S&P 500 Index Fund (SWPPX)',
                'description' => 'A low-cost way to track the performance of the S&P 500 Index.',
                'min_investment' => 15000.00,
                'risk_level' => 'medium',
                'annual_return' => 12.45,
                'total_aum' => 75000000.00,
                'nav_price' => 72.15,
                'inception_date' => '1997-05-19',
            ],
            [
                'name' => 'Fidelity 500 Index Fund (FXAIX)',
                'description' => 'Designed to provide investment results that correspond to the total return of the S&P 500.',
                'min_investment' => 15000.00,
                'risk_level' => 'medium',
                'annual_return' => 12.55,
                'total_aum' => 450000000.00,
                'nav_price' => 162.10,
                'inception_date' => '2011-05-04',
            ],
            [
                'name' => 'Vanguard Information Tech (VITAX)',
                'description' => 'Invests in stocks of companies in the information technology sector.',
                'min_investment' => 100000.00,
                'risk_level' => 'high',
                'annual_return' => 22.30,
                'total_aum' => 55000000.00,
                'nav_price' => 256.40,
                'inception_date' => '2004-01-26',
            ],
            [
                'name' => 'JPMorgan Large Cap Growth (JLGMX)',
                'description' => 'Focuses on companies with strong persistent growth and high quality.',
                'min_investment' => 25000.00,
                'risk_level' => 'high',
                'annual_return' => 17.80,
                'total_aum' => 38000000.00,
                'nav_price' => 88.45,
                'inception_date' => '2004-11-30',
            ],
            [
                'name' => 'Baird Aggregate Bond Fund (BAGIX)',
                'description' => 'Invests in a wide range of investment-grade U.S. bonds.',
                'min_investment' => 15000.00,
                'risk_level' => 'low',
                'annual_return' => 4.80,
                'total_aum' => 32000000.00,
                'nav_price' => 10.42,
                'inception_date' => '2000-09-29',
            ],
            [
                'name' => 'Vanguard Real Estate Index (VGSLX)',
                'description' => 'Provides exposure to companies that purchase and manage real estate.',
                'min_investment' => 15000.00,
                'risk_level' => 'medium',
                'annual_return' => 9.20,
                'total_aum' => 68000000.00,
                'nav_price' => 124.50,
                'inception_date' => '2001-11-12',
            ],
            [
                'name' => 'Fidelity Select Software (FSCSX)',
                'description' => 'Focuses on companies engaged in software and computer services.',
                'min_investment' => 20000.00,
                'risk_level' => 'high',
                'annual_return' => 24.50,
                'total_aum' => 15000000.00,
                'nav_price' => 45.12,
                'inception_date' => '1985-07-29',
            ],
            [
                'name' => 'Vanguard Health Care Fund (VGHAX)',
                'description' => 'Invests in stocks of companies in the health care industry.',
                'min_investment' => 50000.00,
                'risk_level' => 'medium',
                'annual_return' => 13.40,
                'total_aum' => 52000000.00,
                'nav_price' => 102.30,
                'inception_date' => '2001-05-14',
            ],
            [
                'name' => 'Franklin Income Fund (FKINX)',
                'description' => 'Aimed at providing high current income and capital appreciation.',
                'min_investment' => 15000.00,
                'risk_level' => 'low',
                'annual_return' => 7.80,
                'total_aum' => 85000000.00,
                'nav_price' => 2.45,
                'inception_date' => '1948-08-31',
            ],
            [
                'name' => 'T. Rowe Price Health Sciences (PRHSX)',
                'description' => 'Invests in companies across the global health sciences landscape.',
                'min_investment' => 15000.00,
                'risk_level' => 'medium',
                'annual_return' => 14.10,
                'total_aum' => 18000000.00,
                'nav_price' => 95.60,
                'inception_date' => '1995-12-29',
            ],
            [
                'name' => 'ClearBridge Aggressive Growth (LMNVX)',
                'description' => 'Invests in companies with rapid growth prospects and strong capital appreciation potential.',
                'min_investment' => 25000.00,
                'risk_level' => 'high',
                'annual_return' => 16.40,
                'total_aum' => 12000000.00,
                'nav_price' => 285.40,
                'inception_date' => '1983-05-11',
            ],
            [
                'name' => 'Ariel Fund (ARGFX)',
                'description' => 'Focuses on undervalued small- and mid-cap companies.',
                'min_investment' => 15000.00,
                'risk_level' => 'medium',
                'annual_return' => 10.90,
                'total_aum' => 3500000.00,
                'nav_price' => 84.15,
                'inception_date' => '1986-11-06',
            ],
            [
                'name' => 'Vanguard Wellington Fund (VWENX)',
                'description' => 'Balanced fund that invests in a mix of stocks and bonds.',
                'min_investment' => 50000.00,
                'risk_level' => 'low',
                'annual_return' => 9.80,
                'total_aum' => 105000000.00,
                'nav_price' => 75.20,
                'inception_date' => '2001-05-14',
            ],
            [
                'name' => 'Fidelity Low-Priced Stock (FLPSX)',
                'description' => 'Invests in small- to mid-cap companies with low share prices.',
                'min_investment' => 15000.00,
                'risk_level' => 'medium',
                'annual_return' => 13.20,
                'total_aum' => 32000000.00,
                'nav_price' => 54.10,
                'inception_date' => '1989-12-27',
            ],
            [
                'name' => 'BlackRock Technology (BGSAX)',
                'description' => 'A concentrated portfolio of high-conviction technology names.',
                'min_investment' => 20000.00,
                'risk_level' => 'high',
                'annual_return' => 23.80,
                'total_aum' => 8500000.00,
                'nav_price' => 18.45,
                'inception_date' => '1999-12-29',
            ],
            [
                'name' => 'Primecap Management Odyssey Aggressive (POAGX)',
                'description' => 'Focuses on long-term capital growth through aggressive investment strategies.',
                'min_investment' => 15000.00,
                'risk_level' => 'high',
                'annual_return' => 18.40,
                'total_aum' => 7500000.00,
                'nav_price' => 48.75,
                'inception_date' => '2004-11-01',
            ],
            [
                'name' => 'Alger Capital Appreciation (ACAAX)',
                'description' => 'Invests in large-cap companies with significant capital appreciation potential.',
                'min_investment' => 15000.00,
                'risk_level' => 'high',
                'annual_return' => 15.60,
                'total_aum' => 14000000.00,
                'nav_price' => 62.30,
                'inception_date' => '1986-10-31',
            ],
            [
                'name' => 'MFS Growth Fund (MFEGX)',
                'description' => 'Invests in companies with above-average earnings growth potential.',
                'min_investment' => 25000.00,
                'risk_level' => 'high',
                'annual_return' => 16.90,
                'total_aum' => 24000000.00,
                'nav_price' => 114.20,
                'inception_date' => '1986-01-02',
            ],
            [
                'name' => 'MainStay WMC Growth Fund (MLRRX)',
                'description' => 'Focuses on large-cap growth stocks with sustainable competitive advantages.',
                'min_investment' => 15000.00,
                'risk_level' => 'medium',
                'annual_return' => 14.50,
                'total_aum' => 11000000.00,
                'nav_price' => 38.60,
                'inception_date' => '2006-03-31',
            ],
            [
                'name' => 'American Funds New Economy (ANEFX)',
                'description' => 'Invests in companies that benefit from innovative technologies and products.',
                'min_investment' => 15000.00,
                'risk_level' => 'high',
                'annual_return' => 17.20,
                'total_aum' => 42000000.00,
                'nav_price' => 52.18,
                'inception_date' => '1983-12-01',
            ],
        ];

        foreach ($funds as $fund) {
            MutualFund::updateOrCreate(
                ['name' => $fund['name']],
                array_merge($fund, [
                    'status' => 'active',
                    'updated_at' => Carbon::now(),
                ])
            );
        }
    }
}
