@props([
    'id',
    'title',
    'position' => 'right',
    'width' => '480px'
])

<!-- The actual DOM structure is generated by JVDrawer.create(), but we can define the content here and have JS mount it, or just use HTML directly if we prefer declarative usage. 
To support declarative Blade usage, we provide the markup and expect JVDrawer.show('{{$id}}') to be called. -->

<div class="jv-drawer-backdrop" id="jv-drawer-backdrop-{{ $id }}" style="display:none;" onclick="JVDrawer.hide('{{ $id }}')"></div>
<div class="jv-drawer" id="jv-drawer-{{ $id }}" role="dialog" aria-modal="true" aria-labelledby="jv-drawer-title-{{ $id }}" data-position="{{ $position }}" data-width="{{ $width }}" style="display:none; @if($position !== 'bottom') width: {{ $width }}; @endif">
    <!-- Mobile handle bar -->
    <div class="jv-drawer-handle d-md-none"></div>
    
    <div class="jv-drawer-header">
        <h3 class="jv-drawer-title" id="jv-drawer-title-{{ $id }}">{{ $title }}</h3>
        <button type="button" class="jv-drawer-close" onclick="JVDrawer.hide('{{ $id }}')" aria-label="Close drawer">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" x2="6" y1="6" y2="18"></line><line x1="6" x2="18" y1="6" y2="18"></line></svg>
        </button>
    </div>
    
    <div class="jv-drawer-body">
        {{ $slot }}
    </div>
</div>
