@extends('layouts.user.app')

@section('title', 'Security Verification')

@section('content')
<link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet">

<div class="container d-flex align-items-center justify-content-center" style="min-height: 80vh;">
    <div class="glass-card p-5 text-center shadow-lg" style="max-width: 500px; background: rgba(16, 18, 27, 0.4); backdrop-filter: blur(20px); border-radius: 32px; border: 1px solid rgba(255,255,255,0.05);">
        <div class="brand-logo mb-4 d-flex justify-content-center">
            <div class="logo-bg-premium" style="display: flex; width: 100%; justify-content: center; align-items: center; margin-bottom: 20px; background: transparent;">
                <img src="{{ asset('assets/img/favicon.svg') }}?v={{ site()->updated_at->timestamp ?? '1' }}" alt="{{site()->name}}" style="width: 100%; height: 100%; object-fit: contain; transform: scale(1.0);">
            </div>
        </div>

        <div class="verify-icon-wrapper mb-4 mx-auto" style="width: 100px; height: 100px; background: rgba(14, 165, 233, 0.1); border-radius: 30px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(14, 165, 233, 0.2);">
            <i class="ri-shield-keyhole-line text-primary" style="font-size: 3.5rem;"></i>
        </div>

        <h2 class="outfit font-weight-bold text-white mb-2">Identity Verification</h2>
        <p class="text-secondary mb-5">Please enter the 6-digit security code generated by your Google Authenticator app to continue.</p>

        <form id="verifyForm" class="w-100">
            @csrf
            <div class="mb-5">
                <input type="text" name="code" class="otp-field w-100" placeholder="000 000" maxlength="6" inputmode="numeric" autocomplete="one-time-code">
            </div>

            <button type="submit" class="btn btn-premium w-100 py-4 outfit font-weight-bold" style="border-radius: 16px; font-size: 1.1rem; letter-spacing: 1px;">
                AUTHORIZE SESSION
            </button>
        </form>

        <div class="mt-5 pt-3 border-top border-dark">
            <a href="{{ route('profile') }}" class="text-secondary small font-weight-bold text-decoration-none hover-primary transition">
                <i class="ri-arrow-left-line me-1"></i> RETURN TO SECURITY SETTINGS
            </a>
        </div>
    </div>
</div>

<style>
    .otp-field {
        background: rgba(0, 0, 0, 0.3) !important;
        border: 2px solid rgba(255, 255, 255, 0.05) !important;
        color: white !important;
        border-radius: 20px !important;
        padding: 24px !important;
        font-size: 2.2rem !important;
        font-weight: 800 !important;
        text-align: center !important;
        font-family: 'Outfit', sans-serif !important;
        letter-spacing: 8px !important;
        transition: all 0.3s ease !important;
    }

    .otp-field:focus {
        border-color: var(--accent-primary) !important;
        background: rgba(0, 0, 0, 0.4) !important;
        box-shadow: 0 0 25px rgba(14, 165, 233, 0.15) !important;
        outline: none !important;
    }

    .hover-primary:hover {
        color: var(--accent-primary) !important;
    }

    .transition {
        transition: all 0.2s ease;
    }
</style>

<script>
    document.getElementById('verifyForm').addEventListener('submit', function(e) {
        e.preventDefault();
        const code = document.querySelector('input[name="code"]').value;
        if(code.length < 6) {
            toastr.error("Please enter the complete 6-digit code.");
            return;
        }

        const btn = this.querySelector('button[type="submit"]');
        const originalText = btn.innerText;
        btn.disabled = true;
        btn.innerText = "VALIDATING...";

        fetch("{{ route('verify2fa') }}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': "{{ csrf_token() }}"
            },
            body: JSON.stringify({ code: code })
        })
        .then(res => res.json())
        .then(data => {
            if(data.status) {
                toastr.success(data.status);
                setTimeout(() => window.location.href = "{{ route('profile') }}", 1500);
            } else {
                toastr.error(data.error || "Verification failed. Please try again.");
                btn.disabled = false;
                btn.innerText = originalText;
            }
        })
        .catch(err => {
            toastr.error("A connection error occurred.");
            btn.disabled = false;
            btn.innerText = originalText;
        });
    });
</script>
@endsection
