@extends('layouts.user.app')
@section('title', 'Elevate Your Financial Journey')

@section('content')
<div class="upgrade-wrapper py-5 px-3">
    <!-- Header Section: Calming & Visionary -->
    <div class="text-center mb-5 animate-hero">
        <h1 class="display-4 font-weight-bold text-white mb-3">Elevate Your Strategy</h1>
        <p class="lead text-muted mx-auto" style="max-width: 600px;">
            Experience the full power of {{ site()->name }}. Unlock advanced algorithms, priority flows, and premium asset classes designed for serious growth.
        </p>
    </div>

    <!-- Features Bento: Exciting High-Value Reasons -->
    <div class="container mb-5">
        <div class="row g-4 justify-content-center">
            <div class="col-12 col-lg-4 mb-4">
                <div class="glass-card p-4 h-100 text-center hover-lift d-flex flex-column align-items-center justify-content-center" style="min-height: 220px;">
                    <div class="icon-blob mb-3 bg-primary-soft">
                        <i data-lucide="zap" class="text-primary"></i>
                    </div>
                    <h5 class="text-white">Instant Settlements</h5>
                    <p class="small text-muted mb-0 px-3">Priority processing for all trades and withdrawals.</p>
                </div>
            </div>
            <div class="col-12 col-lg-4">
                <div class="glass-card p-4 h-100 text-center hover-lift d-flex flex-column align-items-center justify-content-center" style="min-height: 220px;">
                    <div class="icon-blob mb-3 bg-warning-soft">
                        <i data-lucide="brain-circuit" class="text-warning"></i>
                    </div>
                    <h5 class="text-white">AI Market Signals</h5>
                    <p class="small text-muted mb-0 px-3">High-conviction signals generated by advanced neural models.</p>
                </div>
            </div>
            <div class="col-12 col-lg-4">
                <div class="glass-card p-4 h-100 text-center hover-lift d-flex flex-column align-items-center justify-content-center" style="min-height: 220px;">
                    <div class="icon-blob mb-3 bg-success-soft">
                        <i data-lucide="gem" class="text-success"></i>
                    </div>
                    <h5 class="text-white">VIP Stock Access</h5>
                    <p class="small text-muted mb-0 px-3">Invest in exclusive equity pools with zero brokerage fees.</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Packages Section -->
    <div class="container">
        <div class="row g-4 justify-content-center">
            @foreach($packages as $package)
            <div class="col-xl-4 col-md-6 mb-4">
                <div class="glass-card-premium h-100 shadow-lg {{ $user->package_id == $package->id ? 'border-primary' : '' }} {{ $package->is_restricted ? 'restricted-plan' : '' }}">
                    <div class="card-header-img-wrapper">
                        <img src="{{ url('storage/image/' . ($package->image ?? 'default_investment.png')) }}" alt="{{ $package->name }}" style="width: 100%; height: 100%; object-fit: cover;">
                        <div class="card-header-overlay"></div>
                        

                        @if($package->is_restricted)
                        <div style="position: absolute; top: 12px; left: 12px; z-index: 10;">
                            <span class="badge badge-approval px-3 py-2">
                                <i data-lucide="lock" style="width:10px; display:inline-block; vertical-align:middle;" class="mr-1"></i> SUBJECT TO APPROVAL
                            </span>
                        </div>
                        @endif
                    </div>

                    <div class="card-body-premium pt-0">
                        <div class="package-icon-overlay" style="margin-top: -30px; margin-bottom: 20px; position: relative; z-index: 5;">
                            <div class="bg-dark rounded-circle d-flex align-items-center justify-content-center shadow-lg border {{ $package->is_restricted ? 'border-warning' : 'border-primary' }} border-opacity-25" style="width: 60px; height: 60px; background: #0a0b0e !important;">
                                <i data-lucide="{{ $package->is_restricted ? 'shield-check' : 'medal' }}" class="{{ $package->is_restricted ? 'text-warning' : 'text-primary' }}" style="width: 24px; height: 24px;"></i>
                            </div>
                        </div>

                        <div class="mb-4">
                            <h3 class="outfit font-weight-bold mb-1 text-white">{{ $package->name }}</h3>
                            <div class="price-tag">
                                <span class="h2 font-weight-bold text-white">${{ number_format($package->amount) }}</span>
                                <span class="text-secondary small">/ starting capital</span>
                            </div>
                        </div>

                        <div class="feature-list mb-4 flex-grow-1">
                            <div class="d-flex align-items-center mb-2">
                                <i data-lucide="check-circle" class="text-primary me-2" style="width: 14px;"></i>
                                <span class="small text-secondary">Daily Limit: {{ $package->daily_trade }} Trades</span>
                            </div>
                            <div class="d-flex align-items-center mb-2">
                                <i data-lucide="check-circle" class="text-primary me-2" style="width: 14px;"></i>
                                <span class="small text-secondary">Min Deposit: ${{ number_format($package->min_deposit) }}</span>
                            </div>
                            @if(isset($package->features) && is_countable($package->features))
                                @foreach($package->features as $feature)
                                <div class="d-flex align-items-center mb-2">
                                    <i data-lucide="star" class="text-warning me-2" style="width: 14px;"></i>
                                    <span class="small text-secondary">{{ ucwords(str_replace('_', ' ', $feature)) }}</span>
                                </div>
                                @endforeach
                            @endif
                        </div>

                        @if($user->package_id == $package->id)
                            <button class="btn btn-primary-gradient w-100 py-3 font-weight-bold shadow-lg disabled" style="cursor: not-allowed;" disabled>CURRENT PLAN</button>
                        @elseif($user->package && $package->amount < $user->package->amount)
                            <button class="btn btn-glass w-100 py-3 disabled" disabled>ALREADY ACTIVE</button>
                        @elseif($package->is_restricted)
                            {{-- Restricted plan: show request flow --}}
                            @if($user->basic_plan_approved == 0)
                                <button class="btn btn-request-access w-100 py-3 font-weight-bold shadow-lg" id="requestBasicBtn" onclick="requestBasicAccess()">
                                    <i data-lucide="send" style="width:16px; display:inline-block; vertical-align:middle;" class="mr-2"></i> REQUEST ACCESS
                                </button>
                                <p class="text-center text-muted x-small mt-2 mb-0">Requires admin review & approval</p>
                            @elseif($user->basic_plan_approved == 2)
                                <button class="btn btn-pending w-100 py-3 font-weight-bold" disabled>
                                    <span class="spinner-border spinner-border-sm mr-2" role="status"></span> REQUEST PENDING
                                </button>
                                <p class="text-center text-warning x-small mt-2 mb-0">Your request is under review</p>
                            @elseif($user->basic_plan_approved == 1)
                                <a href="{{ route('deposit') }}" class="btn btn-primary-gradient w-100 py-3 font-weight-bold shadow-lg">
                                    <i data-lucide="check-circle" style="width:16px; display:inline-block; vertical-align:middle;" class="mr-2"></i> UPGRADE NOW
                                </a>
                                <p class="text-center text-success x-small mt-2 mb-0">Access approved — proceed to deposit</p>
                            @endif
                        @else
                            <a href="{{ route('deposit') }}" class="btn btn-primary-gradient w-100 py-3 font-weight-bold shadow-lg">
                                UPGRADE NOW
                            </a>
                        @endif
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</div>

<style>
    .upgrade-wrapper {
        min-height: 100vh;
        background: radial-gradient(circle at top right, rgba(59, 130, 246, 0.08), transparent),
                    radial-gradient(circle at bottom left, rgba(139, 92, 246, 0.08), transparent);
    }
    .display-4 { font-family: 'Outfit', sans-serif; letter-spacing: -1px; }
    .glass-card {
        background: rgba(255, 255, 255, 0.03);
        backdrop-filter: blur(12px);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 20px;
        transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
    }
    .hover-lift:hover {
        transform: translateY(-8px);
        background: rgba(255, 255, 255, 0.05);
        border-color: rgba(255, 255, 255, 0.2);
    }
    .icon-blob {
        width: 60px;
        height: 60px;
        border-radius: 18px;
        display: flex;
        align-items: center;
        justify-content: center;
        margin: 0 auto;
    }
    .bg-primary-soft { background: rgba(59, 130, 246, 0.1); }
    .bg-warning-soft { background: rgba(245, 158, 11, 0.1); }
    .bg-success-soft { background: rgba(255, 51, 51, 0.1); }
    
    .package-card {
        border: 1px solid rgba(255, 255, 255, 0.1);
        position: relative;
        overflow: hidden;
    }
    .package-card.current-plan {
        border: 1px solid var(--primary);
        background: rgba(59, 130, 246, 0.05);
    }
    .btn-primary-gradient {
        background: linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%);
        border: none;
        border-radius: 12px;
        color: white;
        transition: all 0.3s ease;
    }
    .btn-primary-gradient:hover {
        transform: scale(1.02);
        box-shadow: 0 10px 25px rgba(59, 130, 246, 0.4);
    }
    .btn-glass {
        background: rgba(255,255,255,0.05);
        border: 1px solid rgba(255,255,255,0.1);
        border-radius: 12px;
        color: rgba(255,255,255,0.5);
    }
    .badge-primary-glass {
        background: rgba(59, 130, 246, 0.2);
        color: #60a5fa;
        font-size: 0.7rem;
        padding: 4px 10px;
        border-radius: 20px;
    }
    
    @keyframes fadeInUp {
        from { opacity: 0; transform: translateY(20px); }
        to { opacity: 1; transform: translateY(0); }
    }
    .animate-hero { animation: fadeInUp 0.8s ease-out; }

    /* Restricted Plan Styles */
    .restricted-plan {
        border: 1px solid rgba(245, 158, 11, 0.3) !important;
        position: relative;
    }
    .restricted-plan::before {
        content: '';
        position: absolute;
        inset: 0;
        border-radius: inherit;
        background: linear-gradient(135deg, rgba(245, 158, 11, 0.03) 0%, transparent 60%);
        pointer-events: none;
        z-index: 0;
    }
    .badge-approval {
        background: rgba(245, 158, 11, 0.2);
        color: #fbbf24;
        font-size: 0.65rem;
        font-weight: 700;
        letter-spacing: 0.5px;
        border-radius: 20px;
        border: 1px solid rgba(245, 158, 11, 0.3);
    }
    .btn-request-access {
        background: linear-gradient(135deg, #f59e0b 0%, #d97706 100%);
        border: none;
        border-radius: 12px;
        color: white;
        transition: all 0.3s ease;
        letter-spacing: 0.5px;
    }
    .btn-request-access:hover {
        transform: scale(1.02);
        box-shadow: 0 10px 25px rgba(245, 158, 11, 0.4);
        color: white;
    }
    .btn-pending {
        background: rgba(245, 158, 11, 0.15);
        border: 1px solid rgba(245, 158, 11, 0.3);
        border-radius: 12px;
        color: #fbbf24;
        letter-spacing: 0.5px;
        animation: pulseGlow 2s infinite;
    }
    @keyframes pulseGlow {
        0%, 100% { box-shadow: 0 0 5px rgba(245, 158, 11, 0.1); }
        50% { box-shadow: 0 0 20px rgba(245, 158, 11, 0.3); }
    }
</style>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        if (typeof lucide !== 'undefined') lucide.createIcons();
    });

    function requestBasicAccess() {
        var btn = document.getElementById('requestBasicBtn');
        btn.disabled = true;
        btn.innerHTML = '<span class="spinner-border spinner-border-sm mr-2" role="status"></span> SUBMITTING...';

        $.ajax({
            url: "{{ route('user.request_basic_plan') }}",
            method: "POST",
            data: { _token: "{{ csrf_token() }}" },
            success: function(data) {
                if (data.status) {
                    toastr.success('Your request has been submitted for review.', 'REQUEST SENT');
                    setTimeout(function() { location.reload(); }, 1500);
                } else {
                    toastr.info(data.message, 'INFO');
                    btn.disabled = false;
                    btn.innerHTML = '<i data-lucide="send" style="width:16px; display:inline-block; vertical-align:middle;" class="mr-2"></i> REQUEST ACCESS';
                    if (typeof lucide !== 'undefined') lucide.createIcons();
                }
            },
            error: function() {
                toastr.error('Network error. Please try again.', 'ERROR');
                btn.disabled = false;
                btn.innerHTML = '<i data-lucide="send" style="width:16px; display:inline-block; vertical-align:middle;" class="mr-2"></i> REQUEST ACCESS';
                if (typeof lucide !== 'undefined') lucide.createIcons();
            }
        });
    }
</script>
@endsection
